import type { Product, Category, Review } from "./types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Forest Honey",
    description: "Wild honey harvested from pristine forests",
    image: "/placeholder.svg?height=300&width=400",
    productCount: 12,
  },
  {
    id: "2",
    name: "Organic Honey",
    description: "Certified organic honey from sustainable farms",
    image: "/placeholder.svg?height=300&width=400",
    productCount: 8,
  },
  {
    id: "3",
    name: "Medicinal Honey",
    description: "Therapeutic honey with healing properties",
    image: "/placeholder.svg?height=300&width=400",
    productCount: 6,
  },
  {
    id: "4",
    name: "Combo Packs",
    description: "Curated honey collections for every taste",
    image: "/placeholder.svg?height=300&width=400",
    productCount: 4,
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Himalayan Forest Honey",
    description:
      "Pure, raw honey harvested from the pristine Himalayan forests. Rich in antioxidants and natural enzymes.",
    price: 24.99,
    originalPrice: 29.99,
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "Forest Honey",
    inStock: true,
    rating: 4.8,
    reviewCount: 124,
    features: ["Raw & Unprocessed", "Rich in Antioxidants", "Single Origin"],
    weight: "500g",
    origin: "Himalayan Region",
    isOrganic: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    id: "2",
    name: "Manuka Honey Premium",
    description:
      "Authentic New Zealand Manuka honey with exceptional antibacterial properties and unique flavor profile.",
    price: 89.99,
    originalPrice: 99.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Medicinal Honey",
    inStock: true,
    rating: 4.9,
    reviewCount: 89,
    features: ["UMF 15+", "Antibacterial", "Premium Grade"],
    weight: "250g",
    origin: "New Zealand",
    isOrganic: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    id: "3",
    name: "Wildflower Organic Honey",
    description:
      "Delicate blend of wildflower nectar, certified organic and sustainably harvested from local beekeepers.",
    price: 18.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Organic Honey",
    inStock: true,
    rating: 4.6,
    reviewCount: 67,
    features: ["Certified Organic", "Wildflower Blend", "Local Harvest"],
    weight: "350g",
    origin: "Local Farms",
    isOrganic: true,
    isBestSeller: false,
    isNew: true,
  },
  {
    id: "4",
    name: "Honey Tasting Collection",
    description:
      "Curated selection of 4 premium honey varieties in elegant gift packaging. Perfect for honey enthusiasts.",
    price: 49.99,
    originalPrice: 59.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Combo Packs",
    inStock: true,
    rating: 4.7,
    reviewCount: 45,
    features: ["4 Varieties", "Gift Packaging", "Tasting Notes"],
    weight: "4 x 125g",
    origin: "Various",
    isOrganic: false,
    isBestSeller: false,
    isNew: true,
  },
  {
    id: "5",
    name: "Acacia Honey Pure",
    description: "Light, delicate acacia honey with a mild flavor and slow crystallization. Perfect for daily use.",
    price: 22.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Forest Honey",
    inStock: true,
    rating: 4.5,
    reviewCount: 78,
    features: ["Light Color", "Mild Flavor", "Slow Crystallization"],
    weight: "500g",
    origin: "European Forests",
    isOrganic: false,
    isBestSeller: false,
    isNew: false,
  },
  {
    id: "6",
    name: "Raw Buckwheat Honey",
    description: "Dark, robust buckwheat honey with intense flavor and high mineral content. Excellent for baking.",
    price: 26.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Organic Honey",
    inStock: false,
    rating: 4.4,
    reviewCount: 32,
    features: ["Dark & Robust", "High Minerals", "Raw & Unfiltered"],
    weight: "450g",
    origin: "Organic Farms",
    isOrganic: true,
    isBestSeller: false,
    isNew: false,
  },
]

export const reviews: Review[] = [
  {
    id: "1",
    productId: "1",
    customerName: "Sarah Johnson",
    rating: 5,
    comment: "Absolutely amazing honey! The taste is incredible and you can really tell it's pure and natural.",
    date: "2024-01-15",
    verified: true,
  },
  {
    id: "2",
    productId: "1",
    customerName: "Mike Chen",
    rating: 4,
    comment: "Great quality honey, fast shipping. Will definitely order again.",
    date: "2024-01-10",
    verified: true,
  },
  {
    id: "3",
    productId: "2",
    customerName: "Emma Wilson",
    rating: 5,
    comment: "Worth every penny! The Manuka honey is authentic and has helped with my throat issues.",
    date: "2024-01-08",
    verified: true,
  },
]
